// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqlaO-jzgZqPfwWzcqBBLbE1Fw9jsWrq8',
    appId: '1:810433959568:web:3d12d7378b2b429ed1ea15',
    messagingSenderId: '810433959568',
    projectId: 'fir-temp-69b7c',
    authDomain: 'fir-temp-69b7c.firebaseapp.com',
    databaseURL: 'https://fir-temp-69b7c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fir-temp-69b7c.appspot.com',
    measurementId: 'G-B196REMY7D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAiZ5xp6mDWwwFB9zNv132V99Tt0woH4bU',
    appId: '1:810433959568:android:562f3d3910e69046d1ea15',
    messagingSenderId: '810433959568',
    projectId: 'fir-temp-69b7c',
    databaseURL: 'https://fir-temp-69b7c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fir-temp-69b7c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRHLZkFJe7A76fNkpArJOJLTfkRWcY0Gs',
    appId: '1:810433959568:ios:8dc781808d4814e2d1ea15',
    messagingSenderId: '810433959568',
    projectId: 'fir-temp-69b7c',
    databaseURL: 'https://fir-temp-69b7c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fir-temp-69b7c.appspot.com',
    iosBundleId: 'com.example.firebaseTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRHLZkFJe7A76fNkpArJOJLTfkRWcY0Gs',
    appId: '1:810433959568:ios:8dc781808d4814e2d1ea15',
    messagingSenderId: '810433959568',
    projectId: 'fir-temp-69b7c',
    databaseURL: 'https://fir-temp-69b7c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fir-temp-69b7c.appspot.com',
    iosBundleId: 'com.example.firebaseTest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAqlaO-jzgZqPfwWzcqBBLbE1Fw9jsWrq8',
    appId: '1:810433959568:web:078340e78845452ad1ea15',
    messagingSenderId: '810433959568',
    projectId: 'fir-temp-69b7c',
    authDomain: 'fir-temp-69b7c.firebaseapp.com',
    databaseURL: 'https://fir-temp-69b7c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fir-temp-69b7c.appspot.com',
    measurementId: 'G-D8XNB78H5C',
  );
}
