name: firebase_test
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.6
  firebase_core: ^2.30.1
  cloud_firestore: ^4.17.2
  flutter_riverpod: ^2.0.0
  provider: ^6.1.2
  freezed_annotation: ^2.2.1
  firebase_auth: ^4.19.4
  gap: ^3.0.1
  go_router: ^14.0.1
  flutter_easyloading: ^3.0.5
  flutter_secure_storage: ^4.2.1
  hooks_riverpod: ^2.6.1
  http: ^1.2.2
  tuple: ^2.0.2
  mockito: ^5.4.4
  intl: ^0.20.0
  flutter_hooks: ^0.18.6
  shared_preferences: ^2.5.3
  


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

  # freezed
  freezed: ^2.2.1
  riverpod_generator: ^2.3.10
  build_runner: ^2.3.2
  json_serializable: ^6.5.4


flutter:
  uses-material-design: true
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
